// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmj5QwRa_RzA_UeTq_LDsFLuX6CBJ8PgI',
    appId: '1:11822329542:web:111b18a5b66f48b58831c7',
    messagingSenderId: '11822329542',
    projectId: 'be-there-polyhacks',
    authDomain: 'be-there-polyhacks.firebaseapp.com',
    databaseURL: 'https://be-there-polyhacks-default-rtdb.firebaseio.com',
    storageBucket: 'be-there-polyhacks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC42Hg2n3h0sHxSWnF0vjD0TTsurM8RDOo',
    appId: '1:11822329542:android:1f5979db594318c78831c7',
    messagingSenderId: '11822329542',
    projectId: 'be-there-polyhacks',
    databaseURL: 'https://be-there-polyhacks-default-rtdb.firebaseio.com',
    storageBucket: 'be-there-polyhacks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi1x0m9_qcUxS19kfFaBX1w8Ov-zBExDg',
    appId: '1:11822329542:ios:5aa73c6198fb0a1d8831c7',
    messagingSenderId: '11822329542',
    projectId: 'be-there-polyhacks',
    databaseURL: 'https://be-there-polyhacks-default-rtdb.firebaseio.com',
    storageBucket: 'be-there-polyhacks.appspot.com',
    iosClientId: '11822329542-r4p1ldghko6q81gjeg049ntukbqhj96s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bethere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi1x0m9_qcUxS19kfFaBX1w8Ov-zBExDg',
    appId: '1:11822329542:ios:5aa73c6198fb0a1d8831c7',
    messagingSenderId: '11822329542',
    projectId: 'be-there-polyhacks',
    databaseURL: 'https://be-there-polyhacks-default-rtdb.firebaseio.com',
    storageBucket: 'be-there-polyhacks.appspot.com',
    iosClientId: '11822329542-r4p1ldghko6q81gjeg049ntukbqhj96s.apps.googleusercontent.com',
    iosBundleId: 'com.example.bethere',
  );
}
